### ISSUE TITLE
API endpoints for contractors

### ISSUE THREAD

**Issue by mheadd** [openpermit/openpermit.github.io#23]
The developing BLDS standard includes information on contractors associated with a permit, and it is likely that jurisdictions will have this data available. Should there be endpoints to obtain contractor information?

Perhaps something like this :

Retrieve contractors for a specific permit:

<pre>
http://epermithub.com/permits/BLD-34354-001/contractors/
</pre>

Retrieve a list of contractors:

<pre>
http://epermithub.com/contractors/
</pre>

Retrieve details for a specific contractor:

<pre>
http://epermithub.com/contractors/1234567890
</pre>

**Comment by mmartin78** [comment]
Sounds like this would be very useful. Does this information normally include other professionals such as architects and engineers? or just the contractor that applied for the permit?

**Comment by mheadd** [comment]
Some jurisdictions may make other kinds of professional information available, but at a minimum most will have the contractor information.

**Comment by mmartin78** [comment]
This has been added.
